---
title: "RaincloudPlots"
author: "Marie Mückstein"
date: "29 6 2021"
output:
  html_document:
    keep_md: TRUE
---

```{r setup, include = FALSE}
library(tidyverse)
library(here)
library(rmarkdown)

knitr::opts_chunk$set(
  echo = TRUE,
  dev = "ragg_png",
  dpi = 320,
  out.width = "90%",
  fig.width = 8,
  fig.asp = 0.618,
  fig.retina = 2,
  fig.align = "center",
  fig.show = "hold",
  fig.path = here("figure" ,"figure-")
)

```

## Create Raincloud Plots
Plots and functions are based on the following scripts: https://github.com/RainCloudPlots/RainCloudPlots/tree/master/tutorial_R

### 1. Load specific package versions

```{r loadPackageEnvironment}
renv::restore()
```

### 2. Load Raincloud File 

```{r loadScript}
source(here("R-Function", "R_rainclouds.R"))
source(here("R-Function", "summarySE.R"))
```

### 3. Load and prepare data

```{r loadData}
data <-
  read.table(here("data", "PMF03_performance.csv"),
             sep = ";",
             header  = T) %>%
  mutate_if(is.character, as.factor) %>%
  mutate(
    timepoint = fct_recode(timepoint, "Pre" = "pre", "Post" = "post"),
    timepoint = fct_relevel(timepoint, c("Pre", "Post")),
    mapping = fct_recode(mapping, "compatible" = "comp", "incompatible" = "incomp")
  )
head(data)
str(data)
```


### 4. Calculate group means
```{r summary}
summaryDT <- summarySE(data, groupvars = c("timepoint", "mapping", "condition"), measurevar = "pHit.pFa_DT", na.rm =T)
```


### 5. Define Raincloud theme
```{r raincloudTheme}
raincloud_theme <- theme(
  text = element_text(size = 10),
  axis.title.x = element_text(size = 16),
  axis.title.y = element_text(size = 16),
  axis.text = element_text(size = 14),
  legend.title = element_text(size = 16),
  legend.text = element_text(size = 16),
  strip.text = element_text(size = 16),
  legend.position = "right",
  plot.title = element_text(
    lineheight = .8,
    face = "bold",
    size = 16
  ),
  panel.border = element_blank(),
  panel.grid.minor = element_blank(),
  panel.grid.major = element_blank(),
  axis.line.x = element_line(
    colour = 'black',
    size = 0.5,
    linetype = 'solid'
  ),
  axis.line.y = element_line(
    colour = 'black',
    size = 0.5,
    linetype = 'solid'
  )
)
```

### 6. Create Raincloud plots

```{r raincloudPlotBoxplot, fig.height=6}
ggplot(data, aes(x = timepoint, y = pHit.pFa_DT, fill = mapping)) +
  geom_flat_violin(
    aes(fill = mapping),
    position = position_nudge(x = .15, y = 0),
    adjust = 1.5,
    trim = FALSE,
    alpha = .4,
    colour = NA,
    show.legend = FALSE
  ) +
  geom_point(
    aes(
      x = as.numeric(timepoint) + .25,
      y = pHit.pFa_DT,
      colour = mapping
    ),
    position = position_jitter(width = .05),
    size = 1.5,
    shape = 20,
    show.legend = FALSE
  ) +
  geom_boxplot(
    aes(x = timepoint, y = pHit.pFa_DT, fill = mapping),
    outlier.shape = NA,
    alpha = .7,
    width = .2,
    colour = "black"
  ) +
  facet_grid(. ~ condition) +
  scale_colour_manual(values = c("#005824", "#990000")) +
  scale_fill_manual(values = c("#005824", "#990000")) +
  labs(title = "Dual-task Performance for each Intervention Group and Mapping",
       subtitle = "Showing boxplot and distribution") +
  xlab("") +
  ylab("Performance p(hit)-p(fa)") +
  theme_classic() +
  raincloud_theme

```

```{r raincloudPlotPoints, fig.hight = 6}
ggplot(data, aes(x = timepoint, y = pHit.pFa_DT, fill = mapping)) +
  geom_flat_violin(
    aes(fill = mapping),
    position = position_nudge(x = .1, y = 0),
    adjust = 1.5,
    trim = FALSE,
    alpha = .4,
    colour = NA,
    show.legend = FALSE
  ) +
  geom_point(
    aes(
      x = as.numeric(timepoint) + .2,
      y = pHit.pFa_DT,
      colour = mapping
    ),
    position = position_jitter(width = .05),
    size = 1.5,
    shape = 20,
    show.legend = FALSE
  ) +
  geom_line(
    data = summaryDT,
    aes(
      x = as.numeric(timepoint) - .1,
      y = pHit.pFa_DT_mean,
      group = mapping,
      colour = mapping
    ),
    linetype = 1,
    size = 1
  ) +
  geom_point(
    data = summaryDT,
    aes(
      x = as.numeric(timepoint) - .1,
      y = pHit.pFa_DT_mean,
      group = mapping,
      colour = mapping
    ),
    shape = 18,
    size = 2
  ) +
  geom_errorbar(
    data = summaryDT,
    aes(
      x = as.numeric(timepoint) - .1,
      y = pHit.pFa_DT_mean,
      group = mapping,
      colour = mapping,
      ymin = pHit.pFa_DT_mean - se,
      ymax = pHit.pFa_DT_mean + se
    ),
    width = .05
  ) +
  facet_grid(. ~ condition) +
  scale_colour_manual(values = c("#005824", "#990000")) +
  scale_fill_manual(values = c("#005824", "#990000")) +
  labs(title = "Dual-task Performance for each Intervention Group and Mapping",
       subtitle = "Showing means, standard error and distribution") +
  xlab("") +
  ylab("Performance p(hit)-p(fa)") +
  theme_classic() +
  raincloud_theme

```

```{r raincloudPlotPosition, fig.hight = 6}
ggplot(data, aes(x = timepoint, y = pHit.pFa_DT, fill = mapping)) +
  geom_flat_violin(
    aes(fill = mapping),
    position = position_nudge(x = .1, y = 0),
    adjust = 1.5,
    trim = FALSE,
    alpha = .4,
    colour = NA
  ) +
  geom_point(
    aes(
      x = as.numeric(timepoint) - .2,
      y = pHit.pFa_DT,
      colour = mapping
    ),
    position = position_jitter(width = .05),
    size = 1,
    shape = 20,
    show.legend = FALSE,
    alpha = 0.4
  ) +
  geom_line(
    data = summaryDT,
    aes(
      x = as.numeric(timepoint),
      y = pHit.pFa_DT_mean,
      group = mapping,
      colour = mapping
    ),
    linetype = 3,
    size = 1
  ) +
  geom_point(
    data = summaryDT,
    aes(
      x = as.numeric(timepoint),
      y = pHit.pFa_DT_mean,
      group = mapping,
      colour = mapping
    ),
    shape = 18,
    size = 2
  ) +
  geom_errorbar(
    data = summaryDT,
    aes(
      x = as.numeric(timepoint),
      y = pHit.pFa_DT_mean,
      group = mapping,
      colour = mapping,
      ymin = pHit.pFa_DT_mean - se,
      ymax = pHit.pFa_DT_mean + se
    ),
    width = .05
  ) +
  facet_grid(. ~ condition) +
  scale_colour_manual(values = c("#005824", "#990000")) +
  scale_fill_manual(values = c("#005824", "#990000")) +
  labs(title = "Dual-task Performance for each Intervention Group and Mapping",
       subtitle = "Showing means, standard error and distribution") +
  xlab("") +
  ylab("Performance p(hit)-p(fa)") +
  theme_classic() +
  raincloud_theme

```